<?php
/**
 * QuotationsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\cargoboard
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * &lt;h4&gt;Authentication.&lt;/h4&gt; &lt;p&gt;Authentication is done with X-API-KEY. You can request a key via mail to api@cargoboard.com.
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: api@cargoboard.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\cargoboard\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use kruegge82\cargoboard\ApiException;
use kruegge82\cargoboard\Configuration;
use kruegge82\cargoboard\HeaderSelector;
use kruegge82\cargoboard\ObjectSerializer;

/**
 * QuotationsApi Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\cargoboard
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class QuotationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'bookAnOrderBasedOnAQuotation' => [
            'application/json',
        ],
        'getAQuotation' => [
            'application/json',
        ],
        'getQuotations' => [
            'application/json',
        ],
        'placeAQuotation' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bookAnOrderBasedOnAQuotation
     *
     * Book an Order Based on a Quotation
     *
     * @param  string $id id (required)
     * @param  \kruegge82\cargoboard\Model\CreateOrder $create_order create_order (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bookAnOrderBasedOnAQuotation'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoboard\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \kruegge82\cargoboard\Model\ResponseCreateOrder
     */
    public function bookAnOrderBasedOnAQuotation($id, $create_order, string $contentType = self::contentTypes['bookAnOrderBasedOnAQuotation'][0])
    {
        list($response) = $this->bookAnOrderBasedOnAQuotationWithHttpInfo($id, $create_order, $contentType);
        return $response;
    }

    /**
     * Operation bookAnOrderBasedOnAQuotationWithHttpInfo
     *
     * Book an Order Based on a Quotation
     *
     * @param  string $id (required)
     * @param  \kruegge82\cargoboard\Model\CreateOrder $create_order (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bookAnOrderBasedOnAQuotation'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoboard\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \kruegge82\cargoboard\Model\ResponseCreateOrder, HTTP status code, HTTP response headers (array of strings)
     */
    public function bookAnOrderBasedOnAQuotationWithHttpInfo($id, $create_order, string $contentType = self::contentTypes['bookAnOrderBasedOnAQuotation'][0])
    {
        $request = $this->bookAnOrderBasedOnAQuotationRequest($id, $create_order, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\kruegge82\cargoboard\Model\ResponseCreateOrder',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\kruegge82\cargoboard\Model\ResponseCreateOrder',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kruegge82\cargoboard\Model\ResponseCreateOrder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation bookAnOrderBasedOnAQuotationAsync
     *
     * Book an Order Based on a Quotation
     *
     * @param  string $id (required)
     * @param  \kruegge82\cargoboard\Model\CreateOrder $create_order (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bookAnOrderBasedOnAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bookAnOrderBasedOnAQuotationAsync($id, $create_order, string $contentType = self::contentTypes['bookAnOrderBasedOnAQuotation'][0])
    {
        return $this->bookAnOrderBasedOnAQuotationAsyncWithHttpInfo($id, $create_order, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bookAnOrderBasedOnAQuotationAsyncWithHttpInfo
     *
     * Book an Order Based on a Quotation
     *
     * @param  string $id (required)
     * @param  \kruegge82\cargoboard\Model\CreateOrder $create_order (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bookAnOrderBasedOnAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bookAnOrderBasedOnAQuotationAsyncWithHttpInfo($id, $create_order, string $contentType = self::contentTypes['bookAnOrderBasedOnAQuotation'][0])
    {
        $returnType = '\kruegge82\cargoboard\Model\ResponseCreateOrder';
        $request = $this->bookAnOrderBasedOnAQuotationRequest($id, $create_order, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bookAnOrderBasedOnAQuotation'
     *
     * @param  string $id (required)
     * @param  \kruegge82\cargoboard\Model\CreateOrder $create_order (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bookAnOrderBasedOnAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function bookAnOrderBasedOnAQuotationRequest($id, $create_order, string $contentType = self::contentTypes['bookAnOrderBasedOnAQuotation'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling bookAnOrderBasedOnAQuotation'
            );
        }

        // verify the required parameter 'create_order' is set
        if ($create_order === null || (is_array($create_order) && count($create_order) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_order when calling bookAnOrderBasedOnAQuotation'
            );
        }


        $resourcePath = '/v1/quotations/{id}/book';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_order)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_order));
            } else {
                $httpBody = $create_order;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAQuotation
     *
     * Get a Quotation
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAQuotation'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoboard\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getAQuotation($id, string $contentType = self::contentTypes['getAQuotation'][0])
    {
        $this->getAQuotationWithHttpInfo($id, $contentType);
    }

    /**
     * Operation getAQuotationWithHttpInfo
     *
     * Get a Quotation
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAQuotation'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoboard\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAQuotationWithHttpInfo($id, string $contentType = self::contentTypes['getAQuotation'][0])
    {
        $request = $this->getAQuotationRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAQuotationAsync
     *
     * Get a Quotation
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAQuotationAsync($id, string $contentType = self::contentTypes['getAQuotation'][0])
    {
        return $this->getAQuotationAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAQuotationAsyncWithHttpInfo
     *
     * Get a Quotation
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAQuotationAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getAQuotation'][0])
    {
        $returnType = '';
        $request = $this->getAQuotationRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAQuotation'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAQuotationRequest($id, string $contentType = self::contentTypes['getAQuotation'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getAQuotation'
            );
        }


        $resourcePath = '/v1/quotations/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getQuotations
     *
     * Get quotations
     *
     * @param  int|null $take Quantity of quotations to take (optional, default to 50)
     * @param  float|null $cursor Cursor for next page of quotations (optional)
     * @param  string[]|null $order_by Order results by properties (optional)
     * @param  string[]|null $filter Filter results by properties (optional)
     * @param  string|null $filter_operator Filter operator. Possible values [AND, OR] (optional, default to 'AND')
     * @param  bool|null $total Get total quantity of quotations (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuotations'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoboard\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \kruegge82\cargoboard\Model\ResponseGetQuotations
     */
    public function getQuotations($take = 50, $cursor = null, $order_by = null, $filter = null, $filter_operator = 'AND', $total = false, string $contentType = self::contentTypes['getQuotations'][0])
    {
        list($response) = $this->getQuotationsWithHttpInfo($take, $cursor, $order_by, $filter, $filter_operator, $total, $contentType);
        return $response;
    }

    /**
     * Operation getQuotationsWithHttpInfo
     *
     * Get quotations
     *
     * @param  int|null $take Quantity of quotations to take (optional, default to 50)
     * @param  float|null $cursor Cursor for next page of quotations (optional)
     * @param  string[]|null $order_by Order results by properties (optional)
     * @param  string[]|null $filter Filter results by properties (optional)
     * @param  string|null $filter_operator Filter operator. Possible values [AND, OR] (optional, default to 'AND')
     * @param  bool|null $total Get total quantity of quotations (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuotations'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoboard\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \kruegge82\cargoboard\Model\ResponseGetQuotations, HTTP status code, HTTP response headers (array of strings)
     */
    public function getQuotationsWithHttpInfo($take = 50, $cursor = null, $order_by = null, $filter = null, $filter_operator = 'AND', $total = false, string $contentType = self::contentTypes['getQuotations'][0])
    {
        $request = $this->getQuotationsRequest($take, $cursor, $order_by, $filter, $filter_operator, $total, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\kruegge82\cargoboard\Model\ResponseGetQuotations',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\kruegge82\cargoboard\Model\ResponseGetQuotations',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kruegge82\cargoboard\Model\ResponseGetQuotations',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getQuotationsAsync
     *
     * Get quotations
     *
     * @param  int|null $take Quantity of quotations to take (optional, default to 50)
     * @param  float|null $cursor Cursor for next page of quotations (optional)
     * @param  string[]|null $order_by Order results by properties (optional)
     * @param  string[]|null $filter Filter results by properties (optional)
     * @param  string|null $filter_operator Filter operator. Possible values [AND, OR] (optional, default to 'AND')
     * @param  bool|null $total Get total quantity of quotations (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuotations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuotationsAsync($take = 50, $cursor = null, $order_by = null, $filter = null, $filter_operator = 'AND', $total = false, string $contentType = self::contentTypes['getQuotations'][0])
    {
        return $this->getQuotationsAsyncWithHttpInfo($take, $cursor, $order_by, $filter, $filter_operator, $total, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getQuotationsAsyncWithHttpInfo
     *
     * Get quotations
     *
     * @param  int|null $take Quantity of quotations to take (optional, default to 50)
     * @param  float|null $cursor Cursor for next page of quotations (optional)
     * @param  string[]|null $order_by Order results by properties (optional)
     * @param  string[]|null $filter Filter results by properties (optional)
     * @param  string|null $filter_operator Filter operator. Possible values [AND, OR] (optional, default to 'AND')
     * @param  bool|null $total Get total quantity of quotations (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuotations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuotationsAsyncWithHttpInfo($take = 50, $cursor = null, $order_by = null, $filter = null, $filter_operator = 'AND', $total = false, string $contentType = self::contentTypes['getQuotations'][0])
    {
        $returnType = '\kruegge82\cargoboard\Model\ResponseGetQuotations';
        $request = $this->getQuotationsRequest($take, $cursor, $order_by, $filter, $filter_operator, $total, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getQuotations'
     *
     * @param  int|null $take Quantity of quotations to take (optional, default to 50)
     * @param  float|null $cursor Cursor for next page of quotations (optional)
     * @param  string[]|null $order_by Order results by properties (optional)
     * @param  string[]|null $filter Filter results by properties (optional)
     * @param  string|null $filter_operator Filter operator. Possible values [AND, OR] (optional, default to 'AND')
     * @param  bool|null $total Get total quantity of quotations (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuotations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getQuotationsRequest($take = 50, $cursor = null, $order_by = null, $filter = null, $filter_operator = 'AND', $total = false, string $contentType = self::contentTypes['getQuotations'][0])
    {








        $resourcePath = '/v1/quotations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $take,
            'take', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_by,
            'orderBy', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            'filter', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_operator,
            'filterOperator', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $total,
            'total', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation placeAQuotation
     *
     * Place a Quotation
     *
     * @param  \kruegge82\cargoboard\Model\CreateQuotation $create_quotation create_quotation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['placeAQuotation'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoboard\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \kruegge82\cargoboard\Model\ResponseCreateQuotation
     */
    public function placeAQuotation($create_quotation, string $contentType = self::contentTypes['placeAQuotation'][0])
    {
        list($response) = $this->placeAQuotationWithHttpInfo($create_quotation, $contentType);
        return $response;
    }

    /**
     * Operation placeAQuotationWithHttpInfo
     *
     * Place a Quotation
     *
     * @param  \kruegge82\cargoboard\Model\CreateQuotation $create_quotation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['placeAQuotation'] to see the possible values for this operation
     *
     * @throws \kruegge82\cargoboard\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \kruegge82\cargoboard\Model\ResponseCreateQuotation, HTTP status code, HTTP response headers (array of strings)
     */
    public function placeAQuotationWithHttpInfo($create_quotation, string $contentType = self::contentTypes['placeAQuotation'][0])
    {
        $request = $this->placeAQuotationRequest($create_quotation, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\kruegge82\cargoboard\Model\ResponseCreateQuotation',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\kruegge82\cargoboard\Model\ResponseCreateQuotation',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kruegge82\cargoboard\Model\ResponseCreateQuotation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation placeAQuotationAsync
     *
     * Place a Quotation
     *
     * @param  \kruegge82\cargoboard\Model\CreateQuotation $create_quotation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['placeAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function placeAQuotationAsync($create_quotation, string $contentType = self::contentTypes['placeAQuotation'][0])
    {
        return $this->placeAQuotationAsyncWithHttpInfo($create_quotation, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation placeAQuotationAsyncWithHttpInfo
     *
     * Place a Quotation
     *
     * @param  \kruegge82\cargoboard\Model\CreateQuotation $create_quotation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['placeAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function placeAQuotationAsyncWithHttpInfo($create_quotation, string $contentType = self::contentTypes['placeAQuotation'][0])
    {
        $returnType = '\kruegge82\cargoboard\Model\ResponseCreateQuotation';
        $request = $this->placeAQuotationRequest($create_quotation, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'placeAQuotation'
     *
     * @param  \kruegge82\cargoboard\Model\CreateQuotation $create_quotation (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['placeAQuotation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function placeAQuotationRequest($create_quotation, string $contentType = self::contentTypes['placeAQuotation'][0])
    {

        // verify the required parameter 'create_quotation' is set
        if ($create_quotation === null || (is_array($create_quotation) && count($create_quotation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_quotation when calling placeAQuotation'
            );
        }


        $resourcePath = '/v1/quotations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_quotation)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_quotation));
            } else {
                $httpBody = $create_quotation;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
