<?php
/**
 * Quotation
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\cargoboard
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * &lt;h4&gt;Authentication.&lt;/h4&gt; &lt;p&gt;Authentication is done with X-API-KEY. You can request a key via mail to api@cargoboard.com.
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: api@cargoboard.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\cargoboard\Model;

use \ArrayAccess;
use \kruegge82\cargoboard\ObjectSerializer;

/**
 * Quotation Class Doc Comment
 *
 * @category Class
 * @package  kruegge82\cargoboard
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Quotation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Quotation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'product' => 'string',
        'transport_type' => 'string',
        'customer_order_code' => 'string',
        'coupon_code' => 'string',
        'wants_export_declaration' => 'bool',
        'wants_climate_neutral_shipment' => 'bool',
        'wants_insurance' => 'bool',
        'incoterm' => 'string',
        'shipper' => '\kruegge82\cargoboard\Model\ShipperQuotation',
        'consignee' => '\kruegge82\cargoboard\Model\ConsigneeQuotation',
        'value_of_goods_amount' => 'float',
        'value_of_goods_currency' => 'string',
        'lines' => '\kruegge82\cargoboard\Model\LineQuotation[]',
        'id' => 'string',
        'status' => 'string',
        'customer_id' => 'string',
        'sequence' => 'float',
        'order_id' => 'string',
        'quotation_id_eikona' => 'string',
        'runtime_days_min' => 'float',
        'runtime_days_max' => 'float',
        'price_amount' => 'float',
        'price_currency' => 'string',
        'price_amount_standard' => 'float',
        'price_currency_standard' => 'string',
        'placed_at' => '\DateTime',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'truck_type' => 'string',
        'domain' => 'string',
        'shipping_partner' => 'string',
        'delivering_partner' => 'string',
        'lines_weight' => 'float',
        'lines_volume' => 'float',
        'lines_pallet_bays' => 'float',
        'lines_loading_meter' => 'float',
        'quantity_of_euro_pallets' => 'object',
        'co2_emission_amount' => 'float',
        'co2_emission_value' => 'float',
        'co2_emission_unit' => 'string',
        'shipment_cost' => 'float',
        'actual_cost' => 'float',
        'actual_price' => 'float',
        'actual_price_standard' => 'float',
        'cost_items' => '\kruegge82\cargoboard\Model\CostItemQuotation[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'product' => null,
        'transport_type' => null,
        'customer_order_code' => null,
        'coupon_code' => null,
        'wants_export_declaration' => null,
        'wants_climate_neutral_shipment' => null,
        'wants_insurance' => null,
        'incoterm' => null,
        'shipper' => null,
        'consignee' => null,
        'value_of_goods_amount' => null,
        'value_of_goods_currency' => null,
        'lines' => null,
        'id' => null,
        'status' => null,
        'customer_id' => null,
        'sequence' => null,
        'order_id' => null,
        'quotation_id_eikona' => null,
        'runtime_days_min' => null,
        'runtime_days_max' => null,
        'price_amount' => null,
        'price_currency' => null,
        'price_amount_standard' => null,
        'price_currency_standard' => null,
        'placed_at' => 'date-time',
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'truck_type' => null,
        'domain' => null,
        'shipping_partner' => null,
        'delivering_partner' => null,
        'lines_weight' => null,
        'lines_volume' => null,
        'lines_pallet_bays' => null,
        'lines_loading_meter' => null,
        'quantity_of_euro_pallets' => null,
        'co2_emission_amount' => null,
        'co2_emission_value' => null,
        'co2_emission_unit' => null,
        'shipment_cost' => null,
        'actual_cost' => null,
        'actual_price' => null,
        'actual_price_standard' => null,
        'cost_items' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'product' => false,
        'transport_type' => false,
        'customer_order_code' => false,
        'coupon_code' => false,
        'wants_export_declaration' => false,
        'wants_climate_neutral_shipment' => false,
        'wants_insurance' => false,
        'incoterm' => false,
        'shipper' => false,
        'consignee' => false,
        'value_of_goods_amount' => false,
        'value_of_goods_currency' => false,
        'lines' => false,
        'id' => false,
        'status' => false,
        'customer_id' => false,
        'sequence' => false,
        'order_id' => false,
        'quotation_id_eikona' => false,
        'runtime_days_min' => false,
        'runtime_days_max' => false,
        'price_amount' => false,
        'price_currency' => false,
        'price_amount_standard' => false,
        'price_currency_standard' => false,
        'placed_at' => false,
        'created_at' => false,
        'updated_at' => false,
        'truck_type' => false,
        'domain' => false,
        'shipping_partner' => false,
        'delivering_partner' => false,
        'lines_weight' => false,
        'lines_volume' => false,
        'lines_pallet_bays' => false,
        'lines_loading_meter' => false,
        'quantity_of_euro_pallets' => false,
        'co2_emission_amount' => false,
        'co2_emission_value' => false,
        'co2_emission_unit' => false,
        'shipment_cost' => false,
        'actual_cost' => false,
        'actual_price' => false,
        'actual_price_standard' => false,
        'cost_items' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'product' => 'product',
        'transport_type' => 'transportType',
        'customer_order_code' => 'customerOrderCode',
        'coupon_code' => 'couponCode',
        'wants_export_declaration' => 'wantsExportDeclaration',
        'wants_climate_neutral_shipment' => 'wantsClimateNeutralShipment',
        'wants_insurance' => 'wantsInsurance',
        'incoterm' => 'incoterm',
        'shipper' => 'shipper',
        'consignee' => 'consignee',
        'value_of_goods_amount' => 'valueOfGoodsAmount',
        'value_of_goods_currency' => 'valueOfGoodsCurrency',
        'lines' => 'lines',
        'id' => 'id',
        'status' => 'status',
        'customer_id' => 'customerId',
        'sequence' => 'sequence',
        'order_id' => 'orderId',
        'quotation_id_eikona' => 'quotationIdEikona',
        'runtime_days_min' => 'runtimeDaysMin',
        'runtime_days_max' => 'runtimeDaysMax',
        'price_amount' => 'priceAmount',
        'price_currency' => 'priceCurrency',
        'price_amount_standard' => 'priceAmountStandard',
        'price_currency_standard' => 'priceCurrencyStandard',
        'placed_at' => 'placedAt',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'truck_type' => 'truckType',
        'domain' => 'domain',
        'shipping_partner' => 'shippingPartner',
        'delivering_partner' => 'deliveringPartner',
        'lines_weight' => 'linesWeight',
        'lines_volume' => 'linesVolume',
        'lines_pallet_bays' => 'linesPalletBays',
        'lines_loading_meter' => 'linesLoadingMeter',
        'quantity_of_euro_pallets' => 'quantityOfEuroPallets',
        'co2_emission_amount' => 'co2EmissionAmount',
        'co2_emission_value' => 'co2EmissionValue',
        'co2_emission_unit' => 'co2EmissionUnit',
        'shipment_cost' => 'shipmentCost',
        'actual_cost' => 'actualCost',
        'actual_price' => 'actualPrice',
        'actual_price_standard' => 'actualPriceStandard',
        'cost_items' => 'costItems'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'product' => 'setProduct',
        'transport_type' => 'setTransportType',
        'customer_order_code' => 'setCustomerOrderCode',
        'coupon_code' => 'setCouponCode',
        'wants_export_declaration' => 'setWantsExportDeclaration',
        'wants_climate_neutral_shipment' => 'setWantsClimateNeutralShipment',
        'wants_insurance' => 'setWantsInsurance',
        'incoterm' => 'setIncoterm',
        'shipper' => 'setShipper',
        'consignee' => 'setConsignee',
        'value_of_goods_amount' => 'setValueOfGoodsAmount',
        'value_of_goods_currency' => 'setValueOfGoodsCurrency',
        'lines' => 'setLines',
        'id' => 'setId',
        'status' => 'setStatus',
        'customer_id' => 'setCustomerId',
        'sequence' => 'setSequence',
        'order_id' => 'setOrderId',
        'quotation_id_eikona' => 'setQuotationIdEikona',
        'runtime_days_min' => 'setRuntimeDaysMin',
        'runtime_days_max' => 'setRuntimeDaysMax',
        'price_amount' => 'setPriceAmount',
        'price_currency' => 'setPriceCurrency',
        'price_amount_standard' => 'setPriceAmountStandard',
        'price_currency_standard' => 'setPriceCurrencyStandard',
        'placed_at' => 'setPlacedAt',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'truck_type' => 'setTruckType',
        'domain' => 'setDomain',
        'shipping_partner' => 'setShippingPartner',
        'delivering_partner' => 'setDeliveringPartner',
        'lines_weight' => 'setLinesWeight',
        'lines_volume' => 'setLinesVolume',
        'lines_pallet_bays' => 'setLinesPalletBays',
        'lines_loading_meter' => 'setLinesLoadingMeter',
        'quantity_of_euro_pallets' => 'setQuantityOfEuroPallets',
        'co2_emission_amount' => 'setCo2EmissionAmount',
        'co2_emission_value' => 'setCo2EmissionValue',
        'co2_emission_unit' => 'setCo2EmissionUnit',
        'shipment_cost' => 'setShipmentCost',
        'actual_cost' => 'setActualCost',
        'actual_price' => 'setActualPrice',
        'actual_price_standard' => 'setActualPriceStandard',
        'cost_items' => 'setCostItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'product' => 'getProduct',
        'transport_type' => 'getTransportType',
        'customer_order_code' => 'getCustomerOrderCode',
        'coupon_code' => 'getCouponCode',
        'wants_export_declaration' => 'getWantsExportDeclaration',
        'wants_climate_neutral_shipment' => 'getWantsClimateNeutralShipment',
        'wants_insurance' => 'getWantsInsurance',
        'incoterm' => 'getIncoterm',
        'shipper' => 'getShipper',
        'consignee' => 'getConsignee',
        'value_of_goods_amount' => 'getValueOfGoodsAmount',
        'value_of_goods_currency' => 'getValueOfGoodsCurrency',
        'lines' => 'getLines',
        'id' => 'getId',
        'status' => 'getStatus',
        'customer_id' => 'getCustomerId',
        'sequence' => 'getSequence',
        'order_id' => 'getOrderId',
        'quotation_id_eikona' => 'getQuotationIdEikona',
        'runtime_days_min' => 'getRuntimeDaysMin',
        'runtime_days_max' => 'getRuntimeDaysMax',
        'price_amount' => 'getPriceAmount',
        'price_currency' => 'getPriceCurrency',
        'price_amount_standard' => 'getPriceAmountStandard',
        'price_currency_standard' => 'getPriceCurrencyStandard',
        'placed_at' => 'getPlacedAt',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'truck_type' => 'getTruckType',
        'domain' => 'getDomain',
        'shipping_partner' => 'getShippingPartner',
        'delivering_partner' => 'getDeliveringPartner',
        'lines_weight' => 'getLinesWeight',
        'lines_volume' => 'getLinesVolume',
        'lines_pallet_bays' => 'getLinesPalletBays',
        'lines_loading_meter' => 'getLinesLoadingMeter',
        'quantity_of_euro_pallets' => 'getQuantityOfEuroPallets',
        'co2_emission_amount' => 'getCo2EmissionAmount',
        'co2_emission_value' => 'getCo2EmissionValue',
        'co2_emission_unit' => 'getCo2EmissionUnit',
        'shipment_cost' => 'getShipmentCost',
        'actual_cost' => 'getActualCost',
        'actual_price' => 'getActualPrice',
        'actual_price_standard' => 'getActualPriceStandard',
        'cost_items' => 'getCostItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PRODUCT_DIRECT = 'DIRECT';
    public const PRODUCT_EXPRESS = 'EXPRESS';
    public const PRODUCT_EXPRESS_8 = 'EXPRESS_8';
    public const PRODUCT_EXPRESS_10 = 'EXPRESS_10';
    public const PRODUCT_EXPRESS_12 = 'EXPRESS_12';
    public const PRODUCT_EXPRESS_16 = 'EXPRESS_16';
    public const PRODUCT_FIX = 'FIX';
    public const PRODUCT_FIX_8 = 'FIX_8';
    public const PRODUCT_FIX_10 = 'FIX_10';
    public const PRODUCT_FIX_12 = 'FIX_12';
    public const PRODUCT_FIX_16 = 'FIX_16';
    public const PRODUCT_STANDARD = 'STANDARD';
    public const INCOTERM_STANDARD = 'STANDARD';
    public const INCOTERM_DAP_CLEARED = 'DAP_CLEARED';
    public const INCOTERM_DAP_UNCLEARED = 'DAP_UNCLEARED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProductAllowableValues()
    {
        return [
            self::PRODUCT_DIRECT,
            self::PRODUCT_EXPRESS,
            self::PRODUCT_EXPRESS_8,
            self::PRODUCT_EXPRESS_10,
            self::PRODUCT_EXPRESS_12,
            self::PRODUCT_EXPRESS_16,
            self::PRODUCT_FIX,
            self::PRODUCT_FIX_8,
            self::PRODUCT_FIX_10,
            self::PRODUCT_FIX_12,
            self::PRODUCT_FIX_16,
            self::PRODUCT_STANDARD,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIncotermAllowableValues()
    {
        return [
            self::INCOTERM_STANDARD,
            self::INCOTERM_DAP_CLEARED,
            self::INCOTERM_DAP_UNCLEARED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('transport_type', $data ?? [], null);
        $this->setIfExists('customer_order_code', $data ?? [], null);
        $this->setIfExists('coupon_code', $data ?? [], null);
        $this->setIfExists('wants_export_declaration', $data ?? [], false);
        $this->setIfExists('wants_climate_neutral_shipment', $data ?? [], true);
        $this->setIfExists('wants_insurance', $data ?? [], false);
        $this->setIfExists('incoterm', $data ?? [], null);
        $this->setIfExists('shipper', $data ?? [], null);
        $this->setIfExists('consignee', $data ?? [], null);
        $this->setIfExists('value_of_goods_amount', $data ?? [], null);
        $this->setIfExists('value_of_goods_currency', $data ?? [], null);
        $this->setIfExists('lines', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('customer_id', $data ?? [], null);
        $this->setIfExists('sequence', $data ?? [], null);
        $this->setIfExists('order_id', $data ?? [], null);
        $this->setIfExists('quotation_id_eikona', $data ?? [], null);
        $this->setIfExists('runtime_days_min', $data ?? [], null);
        $this->setIfExists('runtime_days_max', $data ?? [], null);
        $this->setIfExists('price_amount', $data ?? [], null);
        $this->setIfExists('price_currency', $data ?? [], null);
        $this->setIfExists('price_amount_standard', $data ?? [], null);
        $this->setIfExists('price_currency_standard', $data ?? [], null);
        $this->setIfExists('placed_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('truck_type', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('shipping_partner', $data ?? [], null);
        $this->setIfExists('delivering_partner', $data ?? [], null);
        $this->setIfExists('lines_weight', $data ?? [], null);
        $this->setIfExists('lines_volume', $data ?? [], null);
        $this->setIfExists('lines_pallet_bays', $data ?? [], null);
        $this->setIfExists('lines_loading_meter', $data ?? [], null);
        $this->setIfExists('quantity_of_euro_pallets', $data ?? [], null);
        $this->setIfExists('co2_emission_amount', $data ?? [], null);
        $this->setIfExists('co2_emission_value', $data ?? [], null);
        $this->setIfExists('co2_emission_unit', $data ?? [], null);
        $this->setIfExists('shipment_cost', $data ?? [], null);
        $this->setIfExists('actual_cost', $data ?? [], null);
        $this->setIfExists('actual_price', $data ?? [], null);
        $this->setIfExists('actual_price_standard', $data ?? [], null);
        $this->setIfExists('cost_items', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['product'] === null) {
            $invalidProperties[] = "'product' can't be null";
        }
        $allowedValues = $this->getProductAllowableValues();
        if (!is_null($this->container['product']) && !in_array($this->container['product'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'product', must be one of '%s'",
                $this->container['product'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getIncotermAllowableValues();
        if (!is_null($this->container['incoterm']) && !in_array($this->container['incoterm'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'incoterm', must be one of '%s'",
                $this->container['incoterm'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['shipper'] === null) {
            $invalidProperties[] = "'shipper' can't be null";
        }
        if ($this->container['consignee'] === null) {
            $invalidProperties[] = "'consignee' can't be null";
        }
        if ($this->container['lines'] === null) {
            $invalidProperties[] = "'lines' can't be null";
        }
        if ($this->container['quantity_of_euro_pallets'] === null) {
            $invalidProperties[] = "'quantity_of_euro_pallets' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets product
     *
     * @return string
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param string $product The product for which a quotation should be received. Possible values: DIRECT, EXPRESS, EXPRESS_8, EXPRESS_10, EXPRESS_12, EXPRESS_16, FIX, FIX_8, FIX_10, FIX_12, FIX_16, STANDARD.
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $allowedValues = $this->getProductAllowableValues();
        if (!in_array($product, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'product', must be one of '%s'",
                    $product,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets transport_type
     *
     * @return string|null
     */
    public function getTransportType()
    {
        return $this->container['transport_type'];
    }

    /**
     * Sets transport_type
     *
     * @param string|null $transport_type Transport type of order. Possible values GROUPAGE, PART_LOAD, DIRECT
     *
     * @return self
     */
    public function setTransportType($transport_type)
    {
        if (is_null($transport_type)) {
            throw new \InvalidArgumentException('non-nullable transport_type cannot be null');
        }
        $this->container['transport_type'] = $transport_type;

        return $this;
    }

    /**
     * Gets customer_order_code
     *
     * @return string|null
     */
    public function getCustomerOrderCode()
    {
        return $this->container['customer_order_code'];
    }

    /**
     * Sets customer_order_code
     *
     * @param string|null $customer_order_code A code applied by customer that will appear on documents as CustomerOrderNo
     *
     * @return self
     */
    public function setCustomerOrderCode($customer_order_code)
    {
        if (is_null($customer_order_code)) {
            throw new \InvalidArgumentException('non-nullable customer_order_code cannot be null');
        }
        $this->container['customer_order_code'] = $customer_order_code;

        return $this;
    }

    /**
     * Gets coupon_code
     *
     * @return string|null
     */
    public function getCouponCode()
    {
        return $this->container['coupon_code'];
    }

    /**
     * Sets coupon_code
     *
     * @param string|null $coupon_code A code applied by customer that will allow for special actions like discount etc.
     *
     * @return self
     */
    public function setCouponCode($coupon_code)
    {
        if (is_null($coupon_code)) {
            throw new \InvalidArgumentException('non-nullable coupon_code cannot be null');
        }
        $this->container['coupon_code'] = $coupon_code;

        return $this;
    }

    /**
     * Gets wants_export_declaration
     *
     * @return bool|null
     */
    public function getWantsExportDeclaration()
    {
        return $this->container['wants_export_declaration'];
    }

    /**
     * Sets wants_export_declaration
     *
     * @param bool|null $wants_export_declaration A service where shipment will be declared for customs. Some customers do this by themselves and others book this option. This service should be only possible if shipment goes to, or comes from a country outside of the EU, like Great Britain, Norway, Switzerland.
     *
     * @return self
     */
    public function setWantsExportDeclaration($wants_export_declaration)
    {
        if (is_null($wants_export_declaration)) {
            throw new \InvalidArgumentException('non-nullable wants_export_declaration cannot be null');
        }
        $this->container['wants_export_declaration'] = $wants_export_declaration;

        return $this;
    }

    /**
     * Gets wants_climate_neutral_shipment
     *
     * @return bool|null
     */
    public function getWantsClimateNeutralShipment()
    {
        return $this->container['wants_climate_neutral_shipment'];
    }

    /**
     * Sets wants_climate_neutral_shipment
     *
     * @param bool|null $wants_climate_neutral_shipment Negative environmental impact will be reduced for this service.
     *
     * @return self
     */
    public function setWantsClimateNeutralShipment($wants_climate_neutral_shipment)
    {
        if (is_null($wants_climate_neutral_shipment)) {
            throw new \InvalidArgumentException('non-nullable wants_climate_neutral_shipment cannot be null');
        }
        $this->container['wants_climate_neutral_shipment'] = $wants_climate_neutral_shipment;

        return $this;
    }

    /**
     * Gets wants_insurance
     *
     * @return bool|null
     */
    public function getWantsInsurance()
    {
        return $this->container['wants_insurance'];
    }

    /**
     * Sets wants_insurance
     *
     * @param bool|null $wants_insurance Cargoboard will organize an insurance for this shipment. goodsValueAmount is necessary if you set wantsInsurance
     *
     * @return self
     */
    public function setWantsInsurance($wants_insurance)
    {
        if (is_null($wants_insurance)) {
            throw new \InvalidArgumentException('non-nullable wants_insurance cannot be null');
        }
        $this->container['wants_insurance'] = $wants_insurance;

        return $this;
    }

    /**
     * Gets incoterm
     *
     * @return string|null
     */
    public function getIncoterm()
    {
        return $this->container['incoterm'];
    }

    /**
     * Sets incoterm
     *
     * @param string|null $incoterm Incoterm - should always be STANDARD and if you ship to Switzerland, or UK it should be DAP
     *
     * @return self
     */
    public function setIncoterm($incoterm)
    {
        if (is_null($incoterm)) {
            throw new \InvalidArgumentException('non-nullable incoterm cannot be null');
        }
        $allowedValues = $this->getIncotermAllowableValues();
        if (!in_array($incoterm, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'incoterm', must be one of '%s'",
                    $incoterm,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['incoterm'] = $incoterm;

        return $this;
    }

    /**
     * Gets shipper
     *
     * @return \kruegge82\cargoboard\Model\ShipperQuotation
     */
    public function getShipper()
    {
        return $this->container['shipper'];
    }

    /**
     * Sets shipper
     *
     * @param \kruegge82\cargoboard\Model\ShipperQuotation $shipper shipper
     *
     * @return self
     */
    public function setShipper($shipper)
    {
        if (is_null($shipper)) {
            throw new \InvalidArgumentException('non-nullable shipper cannot be null');
        }
        $this->container['shipper'] = $shipper;

        return $this;
    }

    /**
     * Gets consignee
     *
     * @return \kruegge82\cargoboard\Model\ConsigneeQuotation
     */
    public function getConsignee()
    {
        return $this->container['consignee'];
    }

    /**
     * Sets consignee
     *
     * @param \kruegge82\cargoboard\Model\ConsigneeQuotation $consignee consignee
     *
     * @return self
     */
    public function setConsignee($consignee)
    {
        if (is_null($consignee)) {
            throw new \InvalidArgumentException('non-nullable consignee cannot be null');
        }
        $this->container['consignee'] = $consignee;

        return $this;
    }

    /**
     * Gets value_of_goods_amount
     *
     * @return float|null
     */
    public function getValueOfGoodsAmount()
    {
        return $this->container['value_of_goods_amount'];
    }

    /**
     * Sets value_of_goods_amount
     *
     * @param float|null $value_of_goods_amount Amount of money - value of goods for insurance or customs
     *
     * @return self
     */
    public function setValueOfGoodsAmount($value_of_goods_amount)
    {
        if (is_null($value_of_goods_amount)) {
            throw new \InvalidArgumentException('non-nullable value_of_goods_amount cannot be null');
        }
        $this->container['value_of_goods_amount'] = $value_of_goods_amount;

        return $this;
    }

    /**
     * Gets value_of_goods_currency
     *
     * @return string|null
     */
    public function getValueOfGoodsCurrency()
    {
        return $this->container['value_of_goods_currency'];
    }

    /**
     * Sets value_of_goods_currency
     *
     * @param string|null $value_of_goods_currency Currency of value of goods. Possible values EUR
     *
     * @return self
     */
    public function setValueOfGoodsCurrency($value_of_goods_currency)
    {
        if (is_null($value_of_goods_currency)) {
            throw new \InvalidArgumentException('non-nullable value_of_goods_currency cannot be null');
        }
        $this->container['value_of_goods_currency'] = $value_of_goods_currency;

        return $this;
    }

    /**
     * Gets lines
     *
     * @return \kruegge82\cargoboard\Model\LineQuotation[]
     */
    public function getLines()
    {
        return $this->container['lines'];
    }

    /**
     * Sets lines
     *
     * @param \kruegge82\cargoboard\Model\LineQuotation[] $lines Line for a product.
     *
     * @return self
     */
    public function setLines($lines)
    {
        if (is_null($lines)) {
            throw new \InvalidArgumentException('non-nullable lines cannot be null');
        }
        $this->container['lines'] = $lines;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Status of order. Possible values INITIALIZED, CREATED, CANCELLED
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets customer_id
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string|null $customer_id Id of customer.
     *
     * @return self
     */
    public function setCustomerId($customer_id)
    {
        if (is_null($customer_id)) {
            throw new \InvalidArgumentException('non-nullable customer_id cannot be null');
        }
        $this->container['customer_id'] = $customer_id;

        return $this;
    }

    /**
     * Gets sequence
     *
     * @return float|null
     */
    public function getSequence()
    {
        return $this->container['sequence'];
    }

    /**
     * Sets sequence
     *
     * @param float|null $sequence Sequence of quotation.
     *
     * @return self
     */
    public function setSequence($sequence)
    {
        if (is_null($sequence)) {
            throw new \InvalidArgumentException('non-nullable sequence cannot be null');
        }
        $this->container['sequence'] = $sequence;

        return $this;
    }

    /**
     * Gets order_id
     *
     * @return string|null
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param string|null $order_id Id of order.
     *
     * @return self
     */
    public function setOrderId($order_id)
    {
        if (is_null($order_id)) {
            throw new \InvalidArgumentException('non-nullable order_id cannot be null');
        }
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets quotation_id_eikona
     *
     * @return string|null
     */
    public function getQuotationIdEikona()
    {
        return $this->container['quotation_id_eikona'];
    }

    /**
     * Sets quotation_id_eikona
     *
     * @param string|null $quotation_id_eikona Quotation id eikona
     *
     * @return self
     */
    public function setQuotationIdEikona($quotation_id_eikona)
    {
        if (is_null($quotation_id_eikona)) {
            throw new \InvalidArgumentException('non-nullable quotation_id_eikona cannot be null');
        }
        $this->container['quotation_id_eikona'] = $quotation_id_eikona;

        return $this;
    }

    /**
     * Gets runtime_days_min
     *
     * @return float|null
     */
    public function getRuntimeDaysMin()
    {
        return $this->container['runtime_days_min'];
    }

    /**
     * Sets runtime_days_min
     *
     * @param float|null $runtime_days_min Runtime days minimum.
     *
     * @return self
     */
    public function setRuntimeDaysMin($runtime_days_min)
    {
        if (is_null($runtime_days_min)) {
            throw new \InvalidArgumentException('non-nullable runtime_days_min cannot be null');
        }
        $this->container['runtime_days_min'] = $runtime_days_min;

        return $this;
    }

    /**
     * Gets runtime_days_max
     *
     * @return float|null
     */
    public function getRuntimeDaysMax()
    {
        return $this->container['runtime_days_max'];
    }

    /**
     * Sets runtime_days_max
     *
     * @param float|null $runtime_days_max Runtime days maximum.
     *
     * @return self
     */
    public function setRuntimeDaysMax($runtime_days_max)
    {
        if (is_null($runtime_days_max)) {
            throw new \InvalidArgumentException('non-nullable runtime_days_max cannot be null');
        }
        $this->container['runtime_days_max'] = $runtime_days_max;

        return $this;
    }

    /**
     * Gets price_amount
     *
     * @return float|null
     */
    public function getPriceAmount()
    {
        return $this->container['price_amount'];
    }

    /**
     * Sets price_amount
     *
     * @param float|null $price_amount Price amount.
     *
     * @return self
     */
    public function setPriceAmount($price_amount)
    {
        if (is_null($price_amount)) {
            throw new \InvalidArgumentException('non-nullable price_amount cannot be null');
        }
        $this->container['price_amount'] = $price_amount;

        return $this;
    }

    /**
     * Gets price_currency
     *
     * @return string|null
     */
    public function getPriceCurrency()
    {
        return $this->container['price_currency'];
    }

    /**
     * Sets price_currency
     *
     * @param string|null $price_currency Status of order. Possible values EUR
     *
     * @return self
     */
    public function setPriceCurrency($price_currency)
    {
        if (is_null($price_currency)) {
            throw new \InvalidArgumentException('non-nullable price_currency cannot be null');
        }
        $this->container['price_currency'] = $price_currency;

        return $this;
    }

    /**
     * Gets price_amount_standard
     *
     * @return float|null
     */
    public function getPriceAmountStandard()
    {
        return $this->container['price_amount_standard'];
    }

    /**
     * Sets price_amount_standard
     *
     * @param float|null $price_amount_standard Price amount standard.
     *
     * @return self
     */
    public function setPriceAmountStandard($price_amount_standard)
    {
        if (is_null($price_amount_standard)) {
            throw new \InvalidArgumentException('non-nullable price_amount_standard cannot be null');
        }
        $this->container['price_amount_standard'] = $price_amount_standard;

        return $this;
    }

    /**
     * Gets price_currency_standard
     *
     * @return string|null
     */
    public function getPriceCurrencyStandard()
    {
        return $this->container['price_currency_standard'];
    }

    /**
     * Sets price_currency_standard
     *
     * @param string|null $price_currency_standard Price currency standard. Possible values EUR
     *
     * @return self
     */
    public function setPriceCurrencyStandard($price_currency_standard)
    {
        if (is_null($price_currency_standard)) {
            throw new \InvalidArgumentException('non-nullable price_currency_standard cannot be null');
        }
        $this->container['price_currency_standard'] = $price_currency_standard;

        return $this;
    }

    /**
     * Gets placed_at
     *
     * @return \DateTime|null
     */
    public function getPlacedAt()
    {
        return $this->container['placed_at'];
    }

    /**
     * Sets placed_at
     *
     * @param \DateTime|null $placed_at Date of order placement
     *
     * @return self
     */
    public function setPlacedAt($placed_at)
    {
        if (is_null($placed_at)) {
            throw new \InvalidArgumentException('non-nullable placed_at cannot be null');
        }
        $this->container['placed_at'] = $placed_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at Date of creation of order
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at Date of update of order
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets truck_type
     *
     * @return string|null
     */
    public function getTruckType()
    {
        return $this->container['truck_type'];
    }

    /**
     * Sets truck_type
     *
     * @param string|null $truck_type Truck type of order. Possible values DIRECT_BUS_PLANE, DIRECT_BUS_PLANE_XXL, DIRECT_TRUCK_7_5, DIRECT_TRUCK_12, DIRECT_TRUCK_40
     *
     * @return self
     */
    public function setTruckType($truck_type)
    {
        if (is_null($truck_type)) {
            throw new \InvalidArgumentException('non-nullable truck_type cannot be null');
        }
        $this->container['truck_type'] = $truck_type;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain Domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets shipping_partner
     *
     * @return string|null
     */
    public function getShippingPartner()
    {
        return $this->container['shipping_partner'];
    }

    /**
     * Sets shipping_partner
     *
     * @param string|null $shipping_partner Shipping partner
     *
     * @return self
     */
    public function setShippingPartner($shipping_partner)
    {
        if (is_null($shipping_partner)) {
            throw new \InvalidArgumentException('non-nullable shipping_partner cannot be null');
        }
        $this->container['shipping_partner'] = $shipping_partner;

        return $this;
    }

    /**
     * Gets delivering_partner
     *
     * @return string|null
     */
    public function getDeliveringPartner()
    {
        return $this->container['delivering_partner'];
    }

    /**
     * Sets delivering_partner
     *
     * @param string|null $delivering_partner Shipping partner
     *
     * @return self
     */
    public function setDeliveringPartner($delivering_partner)
    {
        if (is_null($delivering_partner)) {
            throw new \InvalidArgumentException('non-nullable delivering_partner cannot be null');
        }
        $this->container['delivering_partner'] = $delivering_partner;

        return $this;
    }

    /**
     * Gets lines_weight
     *
     * @return float|null
     */
    public function getLinesWeight()
    {
        return $this->container['lines_weight'];
    }

    /**
     * Sets lines_weight
     *
     * @param float|null $lines_weight Lines weight of quotation.
     *
     * @return self
     */
    public function setLinesWeight($lines_weight)
    {
        if (is_null($lines_weight)) {
            throw new \InvalidArgumentException('non-nullable lines_weight cannot be null');
        }
        $this->container['lines_weight'] = $lines_weight;

        return $this;
    }

    /**
     * Gets lines_volume
     *
     * @return float|null
     */
    public function getLinesVolume()
    {
        return $this->container['lines_volume'];
    }

    /**
     * Sets lines_volume
     *
     * @param float|null $lines_volume Lines volume of quotation.
     *
     * @return self
     */
    public function setLinesVolume($lines_volume)
    {
        if (is_null($lines_volume)) {
            throw new \InvalidArgumentException('non-nullable lines_volume cannot be null');
        }
        $this->container['lines_volume'] = $lines_volume;

        return $this;
    }

    /**
     * Gets lines_pallet_bays
     *
     * @return float|null
     */
    public function getLinesPalletBays()
    {
        return $this->container['lines_pallet_bays'];
    }

    /**
     * Sets lines_pallet_bays
     *
     * @param float|null $lines_pallet_bays Lines pallet bays of quotation.
     *
     * @return self
     */
    public function setLinesPalletBays($lines_pallet_bays)
    {
        if (is_null($lines_pallet_bays)) {
            throw new \InvalidArgumentException('non-nullable lines_pallet_bays cannot be null');
        }
        $this->container['lines_pallet_bays'] = $lines_pallet_bays;

        return $this;
    }

    /**
     * Gets lines_loading_meter
     *
     * @return float|null
     */
    public function getLinesLoadingMeter()
    {
        return $this->container['lines_loading_meter'];
    }

    /**
     * Sets lines_loading_meter
     *
     * @param float|null $lines_loading_meter Lines loading meter of quotation.
     *
     * @return self
     */
    public function setLinesLoadingMeter($lines_loading_meter)
    {
        if (is_null($lines_loading_meter)) {
            throw new \InvalidArgumentException('non-nullable lines_loading_meter cannot be null');
        }
        $this->container['lines_loading_meter'] = $lines_loading_meter;

        return $this;
    }

    /**
     * Gets quantity_of_euro_pallets
     *
     * @return object
     */
    public function getQuantityOfEuroPallets()
    {
        return $this->container['quantity_of_euro_pallets'];
    }

    /**
     * Sets quantity_of_euro_pallets
     *
     * @param object $quantity_of_euro_pallets Quantity of euro pallets from lines.
     *
     * @return self
     */
    public function setQuantityOfEuroPallets($quantity_of_euro_pallets)
    {
        if (is_null($quantity_of_euro_pallets)) {
            throw new \InvalidArgumentException('non-nullable quantity_of_euro_pallets cannot be null');
        }
        $this->container['quantity_of_euro_pallets'] = $quantity_of_euro_pallets;

        return $this;
    }

    /**
     * Gets co2_emission_amount
     *
     * @return float|null
     */
    public function getCo2EmissionAmount()
    {
        return $this->container['co2_emission_amount'];
    }

    /**
     * Sets co2_emission_amount
     *
     * @param float|null $co2_emission_amount CO2 Emission amount of quotation.
     *
     * @return self
     */
    public function setCo2EmissionAmount($co2_emission_amount)
    {
        if (is_null($co2_emission_amount)) {
            throw new \InvalidArgumentException('non-nullable co2_emission_amount cannot be null');
        }
        $this->container['co2_emission_amount'] = $co2_emission_amount;

        return $this;
    }

    /**
     * Gets co2_emission_value
     *
     * @return float|null
     */
    public function getCo2EmissionValue()
    {
        return $this->container['co2_emission_value'];
    }

    /**
     * Sets co2_emission_value
     *
     * @param float|null $co2_emission_value CO2 Emission value of quotation.
     *
     * @return self
     */
    public function setCo2EmissionValue($co2_emission_value)
    {
        if (is_null($co2_emission_value)) {
            throw new \InvalidArgumentException('non-nullable co2_emission_value cannot be null');
        }
        $this->container['co2_emission_value'] = $co2_emission_value;

        return $this;
    }

    /**
     * Gets co2_emission_unit
     *
     * @return string|null
     */
    public function getCo2EmissionUnit()
    {
        return $this->container['co2_emission_unit'];
    }

    /**
     * Sets co2_emission_unit
     *
     * @param string|null $co2_emission_unit CO2 Emission unit of quotation.
     *
     * @return self
     */
    public function setCo2EmissionUnit($co2_emission_unit)
    {
        if (is_null($co2_emission_unit)) {
            throw new \InvalidArgumentException('non-nullable co2_emission_unit cannot be null');
        }
        $this->container['co2_emission_unit'] = $co2_emission_unit;

        return $this;
    }

    /**
     * Gets shipment_cost
     *
     * @return float|null
     */
    public function getShipmentCost()
    {
        return $this->container['shipment_cost'];
    }

    /**
     * Sets shipment_cost
     *
     * @param float|null $shipment_cost Shipment cost of quotation.
     *
     * @return self
     */
    public function setShipmentCost($shipment_cost)
    {
        if (is_null($shipment_cost)) {
            throw new \InvalidArgumentException('non-nullable shipment_cost cannot be null');
        }
        $this->container['shipment_cost'] = $shipment_cost;

        return $this;
    }

    /**
     * Gets actual_cost
     *
     * @return float|null
     */
    public function getActualCost()
    {
        return $this->container['actual_cost'];
    }

    /**
     * Sets actual_cost
     *
     * @param float|null $actual_cost Actual cost of quotation.
     *
     * @return self
     */
    public function setActualCost($actual_cost)
    {
        if (is_null($actual_cost)) {
            throw new \InvalidArgumentException('non-nullable actual_cost cannot be null');
        }
        $this->container['actual_cost'] = $actual_cost;

        return $this;
    }

    /**
     * Gets actual_price
     *
     * @return float|null
     */
    public function getActualPrice()
    {
        return $this->container['actual_price'];
    }

    /**
     * Sets actual_price
     *
     * @param float|null $actual_price Actual price of quotation.
     *
     * @return self
     */
    public function setActualPrice($actual_price)
    {
        if (is_null($actual_price)) {
            throw new \InvalidArgumentException('non-nullable actual_price cannot be null');
        }
        $this->container['actual_price'] = $actual_price;

        return $this;
    }

    /**
     * Gets actual_price_standard
     *
     * @return float|null
     */
    public function getActualPriceStandard()
    {
        return $this->container['actual_price_standard'];
    }

    /**
     * Sets actual_price_standard
     *
     * @param float|null $actual_price_standard Actual standard price of quotation.
     *
     * @return self
     */
    public function setActualPriceStandard($actual_price_standard)
    {
        if (is_null($actual_price_standard)) {
            throw new \InvalidArgumentException('non-nullable actual_price_standard cannot be null');
        }
        $this->container['actual_price_standard'] = $actual_price_standard;

        return $this;
    }

    /**
     * Gets cost_items
     *
     * @return \kruegge82\cargoboard\Model\CostItemQuotation[]|null
     */
    public function getCostItems()
    {
        return $this->container['cost_items'];
    }

    /**
     * Sets cost_items
     *
     * @param \kruegge82\cargoboard\Model\CostItemQuotation[]|null $cost_items cost_items
     *
     * @return self
     */
    public function setCostItems($cost_items)
    {
        if (is_null($cost_items)) {
            throw new \InvalidArgumentException('non-nullable cost_items cannot be null');
        }
        $this->container['cost_items'] = $cost_items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


